kind: ConfigMap
apiVersion: v1
metadata:
  name: zuul
  namespace: dmandry
data:
  main.yaml: |-
    - tenant:
        name: example-tenant
        source:
          gerrit:
            config-projects:
              - zuul-config
            untrusted-projects:
              - test1
          opendev.org:
            untrusted-projects:
              - zuul/zuul-jobs:
                  include:
                    - job
  zuul.conf: >-
    [gearman]

    server=zuul


    [gearman_server]

    start=true


    [zookeeper]

    hosts=zuul:2281

    tls_cert=/var/certs/client.pem

    tls_key=/var/certs/clientkey.pem

    tls_ca=/var/certs/cacert.pem


    [scheduler]

    tenant_config=/etc/zuul/main.yaml


    [connection "gerrit"]

    name=gerrit

    driver=gerrit

    server=gerrit

    sshkey=/var/ssh/zuul

    user=secret

    password=secret

    baseurl=https://gerrit-dmandry.apps.ca-central-1.starter.openshift-online.com

    auth_type=basic

    [connection "opendev.org"]

    name=opendev

    driver=git

    baseurl=https://opendev.org


    [connection "mysql"]

    name=mysql

    driver=sql

    dburi=mysql+pymysql://secret:secret@logs-and-db/secret


    [web]

    root=https://zuul-dmandry.apps.ca-central-1.starter.openshift-online.com

    listen_address=0.0.0.0


    [executor]

    max_starting_builds=1

    private_key_file=/var/ssh/zuul
