kind: ConfigMap
apiVersion: v1
metadata:
  name: zookeeper
  namespace: dmandry
data:
  zoo.cfg: |-
    dataDir=/data
    dataLogDir=/datalog
    tickTime=2000
    maxClientCnxns=1
    initLimit=5
    syncLimit=2
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=6
    maxClientCnxns=60
    standaloneEnabled=true
    admin.enableServer=false
    server.1=172.30.215.243:2888:3888
    serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
    secureClientPort=2281
    ssl.keyStore.location=/var/certs/server.pem
    ssl.trustStore.location=/var/certs/cacert.pem
